# Generated by Django 5.0.6 on 2024-07-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
